//! Replays fixtures generated by running the REAL, unmodified
//! `agent/core/categories.py`, `agent/core/title_classifier.py`, and
//! `agent/core/aggregator.py::Aggregator` directly — see
//! `artifacts/desktop-client/AG-006/generate_golden_fixtures.py`. This is
//! genuine parity verification: the fixtures are Python's actual output,
//! not a hand-derived guess at what it "should" produce.

use chrono::{DateTime, Utc};
use event_contract::{Consent, Signals};
use normalization::{
    categorize, category_label, classify_title, processes_for_category, BucketAccumulator, Tick,
    TitleRules,
};
use serde_json::Value;
use std::collections::BTreeMap;

fn load_fixture(name: &str) -> Value {
    let path = format!("{}/tests/fixtures/{name}", env!("CARGO_MANIFEST_DIR"));
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("failed to read fixture {path}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("failed to parse fixture {path}: {e}"))
}

fn json_string_or_none(value: &Value) -> Option<String> {
    match value {
        Value::Null => None,
        Value::String(s) => Some(s.clone()),
        other => panic!("expected string or null, got {other:?}"),
    }
}

fn json_overrides(value: &Value) -> Option<BTreeMap<String, String>> {
    match value {
        Value::Null => None,
        Value::Object(map) => Some(
            map.iter()
                .map(|(k, v)| (k.clone(), v.as_str().unwrap().to_string()))
                .collect(),
        ),
        other => panic!("expected object or null, got {other:?}"),
    }
}

#[test]
fn categorize_matches_python_for_every_golden_case() {
    let fixture = load_fixture("categorize_cases.json");
    let cases = fixture.as_array().unwrap();
    assert!(
        !cases.is_empty(),
        "fixture must not be empty — a vacuous test proves nothing"
    );

    for case in cases {
        let process_name = json_string_or_none(&case["process_name"]);
        let overrides = json_overrides(&case["overrides"]);
        let expected_category = case["category"].as_str().unwrap();
        let expected_label = case["label"].as_str().unwrap();

        let actual_category = categorize(process_name.as_deref(), overrides.as_ref());
        assert_eq!(
            actual_category, expected_category,
            "categorize({process_name:?}, {overrides:?}) mismatch vs real Python output"
        );
        assert_eq!(category_label(&actual_category), expected_label);
    }
}

#[test]
fn processes_for_category_matches_python() {
    // A subset check, not exact equality: `DEFAULT_CATEGORY_MAP` (Rust)
    // deliberately grew real Linux process names (`chrome`, `ptyxis`,
    // etc. — categories.rs's own doc comment) that
    // `agent/core/categories.py` never had and was never meant to, since
    // Python was Windows-only and the Linux agent is Rust-only. Full
    // byte-for-byte parity with Python remains the goal for every
    // Windows entry Python already knows about; Rust knowing about MORE
    // (Linux) processes on top of that is the intended, not accidental,
    // difference this assertion must allow.
    let fixture = load_fixture("processes_for_category.json");
    let category = fixture["category"].as_str().unwrap();
    let overrides = json_overrides(&fixture["overrides"]);
    let expected: Vec<String> = fixture["processes"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();

    let actual: Vec<String> = processes_for_category(category, overrides.as_ref())
        .into_iter()
        .collect();
    for process in &expected {
        assert!(
            actual.contains(process),
            "Rust's result for category {category:?} is missing {process:?}, which Python's fixture expects"
        );
    }
}

#[test]
fn classify_title_matches_python_including_rule_order_sensitivity() {
    let fixture = load_fixture("classify_title_cases.json");
    let cases = fixture.as_array().unwrap();
    assert!(!cases.is_empty());

    for case in cases {
        let title = json_string_or_none(&case["title"]);
        let rules_value = &case["rules"];
        let rules: TitleRules = rules_value
            .as_object()
            .unwrap()
            .iter()
            .map(|(category, patterns)| {
                let patterns: Vec<String> = patterns
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|p| p.as_str().unwrap().to_string())
                    .collect();
                (category.clone(), patterns)
            })
            .collect();
        let expected = json_string_or_none(&case["result"]);

        let actual = classify_title(title.as_deref(), &rules);
        assert_eq!(
            actual, expected,
            "classify_title({title:?}, {rules:?}) mismatch vs real Python output"
        );
    }
}

#[test]
fn rule_order_actually_flips_the_result_not_a_coincidence() {
    // The fixture already contains this exact pair of cases (same title,
    // same two rules, swapped order, different result) — this test makes
    // the point explicit and self-contained, independent of fixture file
    // contents, so the property survives even if the fixture is regenerated.
    let title = Some("youtube and vk.com both mentioned");
    let media_first: TitleRules = vec![
        ("media".to_string(), vec!["youtube".to_string()]),
        ("communication".to_string(), vec!["vk.com".to_string()]),
    ];
    let communication_first: TitleRules = vec![
        ("communication".to_string(), vec!["vk.com".to_string()]),
        ("media".to_string(), vec!["youtube".to_string()]),
    ];

    assert_eq!(
        classify_title(title, &media_first),
        Some("media".to_string())
    );
    assert_eq!(
        classify_title(title, &communication_first),
        Some("communication".to_string())
    );
}

fn base_time() -> DateTime<Utc> {
    "2026-07-17T12:00:00Z".parse().unwrap()
}

#[allow(clippy::too_many_arguments)] // a terse positional test helper is clearer here than a builder for one-off scenario setup
fn tick(
    at_index: i64,
    interval: f64,
    is_idle: bool,
    process: Option<&str>,
    k: i64,
    mm: i64,
    mc: i64,
    category_override: Option<&str>,
) -> Tick {
    Tick {
        active_process_name: process.map(|s| s.to_string()),
        keyboard_events: k,
        mouse_move_events: mm,
        mouse_click_events: mc,
        is_idle,
        category_override: category_override.map(|s| s.to_string()),
        occurred_at: base_time()
            + chrono::Duration::milliseconds((interval * 1000.0 * at_index as f64) as i64),
        interval_seconds: interval,
    }
}

/// Compares a produced `Signals` against a golden fixture's `signals` JSON
/// object. Scalar/map fields compare via direct JSON equality (unambiguous:
/// numbers and strings have one canonical JSON form). Timestamp-bearing
/// fields (`activity_segments`/`unexplained_gaps`) compare by PARSING both
/// sides into `DateTime<Utc>` and checking the represented instant, not the
/// raw string — chrono serializes as `...Z` while Python's `isoformat()`
/// produces `...+00:00`; these are the same instant in different valid
/// RFC3339 spellings, and a raw string comparison would wrongly fail here.
fn assert_signals_match_fixture(actual: &Signals, expected: &Value, scenario_name: &str) {
    let actual_json = serde_json::to_value(actual).unwrap();

    for field in [
        "active_app_category_seconds",
        "input_activity_events",
        "idle_seconds",
        "active_seconds",
        "git_commits_count",
        "app_seconds",
        "other_app_seconds",
    ] {
        assert_eq!(
            actual_json[field], expected[field],
            "scenario {scenario_name:?}: field {field:?} mismatch"
        );
    }

    for field in ["activity_segments", "unexplained_gaps"] {
        let actual_list = actual_json[field].as_array();
        let expected_list = expected[field].as_array();
        match (actual_list, expected_list) {
            (None, None) => {} // both null (consent off) — fine, already covered by the field being absent/null
            (Some(actual_list), Some(expected_list)) => {
                assert_eq!(actual_list.len(), expected_list.len(), "scenario {scenario_name:?}: field {field:?} length mismatch");
                for (a, e) in actual_list.iter().zip(expected_list.iter()) {
                    assert_eq!(a["category"].as_str(), e.get("category").and_then(|v| v.as_str()), "scenario {scenario_name:?}: {field} category mismatch");
                    assert_eq!(a["duration_seconds"], e["duration_seconds"], "scenario {scenario_name:?}: {field} duration mismatch");
                    let a_started: DateTime<Utc> = a["started_at"].as_str().unwrap().parse().unwrap();
                    let e_started: DateTime<Utc> = e["started_at"].as_str().unwrap().parse().unwrap();
                    assert_eq!(a_started, e_started, "scenario {scenario_name:?}: {field} started_at instant mismatch");
                    let a_ended: DateTime<Utc> = a["ended_at"].as_str().unwrap().parse().unwrap();
                    let e_ended: DateTime<Utc> = e["ended_at"].as_str().unwrap().parse().unwrap();
                    assert_eq!(a_ended, e_ended, "scenario {scenario_name:?}: {field} ended_at instant mismatch");
                }
            }
            _ => panic!("scenario {scenario_name:?}: field {field:?} present/absent mismatch (actual={actual_list:?}, expected={expected_list:?})"),
        }
    }
}

#[test]
fn bucket_accumulation_matches_python_aggregator_for_every_scenario() {
    let fixture = load_fixture("bucket_accumulation_scenarios.json");
    let scenarios = fixture.as_array().unwrap();
    assert!(!scenarios.is_empty());

    // Mirrors artifacts/desktop-client/AG-006/generate_golden_fixtures.py's
    // scenario definitions exactly (consent flags, overrides, thresholds,
    // and the tick sequences) — see that script for the source of truth.
    let mixed_activity_full_consent = {
        let mut acc = BucketAccumulator::new(
            Consent {
                active_app_category: true,
                input_activity_counts: true,
                idle_tracking: true,
                activity_segments: true,
                unexplained_gaps: true,
                git_activity: false,
                app_detail: true,
            },
            BTreeMap::new(),
            900.0,
        );
        acc.accumulate(&tick(1, 2.0, false, Some("code.exe"), 10, 5, 1, None));
        acc.accumulate(&tick(2, 2.0, false, Some("code.exe"), 8, 3, 0, None));
        acc.accumulate(&tick(3, 2.0, false, Some("chrome.exe"), 1, 10, 4, None));
        acc.accumulate(&tick(
            4,
            2.0,
            false,
            Some("unknown-thing.exe"),
            0,
            1,
            0,
            None,
        ));
        acc.flush(None)
    };

    let idle_below_gap_threshold = {
        let mut acc = BucketAccumulator::new(
            Consent {
                active_app_category: true,
                input_activity_counts: true,
                idle_tracking: true,
                activity_segments: true,
                unexplained_gaps: true,
                git_activity: false,
                app_detail: false,
            },
            BTreeMap::new(),
            900.0,
        );
        acc.accumulate(&tick(1, 2.0, false, Some("code.exe"), 5, 0, 0, None));
        acc.accumulate(&tick(2, 2.0, true, None, 0, 0, 0, None));
        acc.accumulate(&tick(3, 2.0, false, Some("code.exe"), 3, 0, 0, None));
        acc.flush(None)
    };

    let minimal_consent = {
        let mut acc = BucketAccumulator::new(
            Consent {
                active_app_category: false,
                input_activity_counts: false,
                idle_tracking: false,
                activity_segments: false,
                unexplained_gaps: false,
                git_activity: false,
                app_detail: false,
            },
            BTreeMap::new(),
            900.0,
        );
        acc.accumulate(&tick(1, 2.0, false, Some("code.exe"), 10, 5, 1, None));
        acc.accumulate(&tick(2, 2.0, true, None, 0, 0, 0, None));
        acc.flush(None)
    };

    let category_override_from_title = {
        let mut acc = BucketAccumulator::new(
            Consent {
                active_app_category: true,
                input_activity_counts: false,
                idle_tracking: false,
                activity_segments: false,
                unexplained_gaps: false,
                git_activity: false,
                app_detail: true,
            },
            BTreeMap::new(),
            900.0,
        );
        acc.accumulate(&tick(
            1,
            2.0,
            false,
            Some("chrome.exe"),
            0,
            0,
            0,
            Some("media"),
        ));
        acc.accumulate(&tick(2, 2.0, false, Some("chrome.exe"), 0, 0, 0, None));
        acc.flush(None)
    };

    let config_category_override = {
        let mut overrides = BTreeMap::new();
        overrides.insert("mytool.exe".to_string(), "task_tracker".to_string());
        let mut acc = BucketAccumulator::new(
            Consent {
                active_app_category: true,
                input_activity_counts: false,
                idle_tracking: false,
                activity_segments: false,
                unexplained_gaps: false,
                git_activity: false,
                app_detail: false,
            },
            overrides,
            900.0,
        );
        acc.accumulate(&tick(1, 2.0, false, Some("mytool.exe"), 0, 0, 0, None));
        acc.flush(None)
    };

    let produced: BTreeMap<&str, Signals> = [
        ("mixed_activity_full_consent", mixed_activity_full_consent),
        ("idle_below_gap_threshold", idle_below_gap_threshold),
        ("minimal_consent", minimal_consent),
        ("category_override_from_title", category_override_from_title),
        ("config_category_override", config_category_override),
    ]
    .into_iter()
    .collect();

    for scenario in scenarios {
        let name = scenario["name"].as_str().unwrap();
        let expected_signals = &scenario["signals"];
        let actual = produced.get(name).unwrap_or_else(|| panic!("no Rust-side scenario constructed for fixture entry {name:?} — fixture and test have drifted"));
        assert_signals_match_fixture(actual, expected_signals, name);
    }
    assert_eq!(
        produced.len(),
        scenarios.len(),
        "every constructed scenario must correspond to a fixture entry, and vice versa"
    );
}
