//! Direct port of the bucket-accumulation logic in
//! `agent/core/aggregator.py` (`Aggregator._accumulate`/`_flush`) — NOT the
//! poll/sleep scheduling loop around it (`Aggregator.run`), which is
//! platform-collector-adapter territory for a later task, not "shared
//! normalization." This module answers "given a sequence of raw signal
//! ticks and a consent configuration, what does one aggregated bucket of
//! signals look like" — the same question `_accumulate`/`_flush` answer,
//! ported field-for-field (see `tests/golden_fixture_tests.rs`, which
//! replays fixtures generated by running the real Python `Aggregator`
//! class directly, not a re-derivation from reading the source alone).

use crate::categories::{categorize, UNKNOWN_CATEGORY};
use chrono::{DateTime, Utc};
use event_contract::{ActivitySegment, Consent, InputActivityEvents, Signals, UnexplainedGap};
use std::collections::BTreeMap;

/// One collector poll's worth of raw signal — mirrors
/// `core/interfaces.py::RawSignalSnapshot`. `active_process_name` is a
/// process name only (e.g. "chrome.exe"), never a window title.
/// `category_override` is the result of the collector's OWN local title
/// classification (see `title_classifier::classify_title`) — the title
/// text itself must never reach this struct, only the already-classified
/// category name, exactly as in the Python source this ports.
#[derive(Debug, Clone)]
pub struct Tick {
    pub active_process_name: Option<String>,
    pub keyboard_events: i64,
    pub mouse_move_events: i64,
    pub mouse_click_events: i64,
    pub is_idle: bool,
    pub category_override: Option<String>,
    /// The instant this tick was observed — used only for segment/gap
    /// timing math, mirroring the Python source's `datetime.now(timezone.utc)`
    /// calls (injected here rather than read from the system clock, so the
    /// accumulator itself stays pure/deterministic and testable).
    pub occurred_at: DateTime<Utc>,
    /// How much wall-clock time this tick represents — the Python source's
    /// `poll_interval_seconds` config value, added unconditionally to
    /// `active_seconds`/`idle_seconds` on every tick regardless of content.
    pub interval_seconds: f64,
}

/// Placeholder key for `app_seconds` when the active window isn't idle but
/// the collector couldn't determine a process name (system dialogs, UAC,
/// secure desktop) — mirrors `aggregator.py::UNKNOWN_APP_LABEL` exactly,
/// including the reasoning: `category_seconds` still gets a real category
/// (`categorize(None) -> "other"`) at that moment, so `app_seconds` needs
/// its own bucket too, or its sum would permanently undercount relative to
/// `category_seconds` for the same period.
pub const UNKNOWN_APP_LABEL: &str = "(без имени процесса)";

/// One accumulating bucket — the pure-logic equivalent of one `Aggregator`
/// instance's bucket state between flushes. Owns the same "open
/// segment/gap survives a flush, only bucket sums reset" invariant as the
/// Python source (see `flush`'s doc comment).
pub struct BucketAccumulator {
    consent: Consent,
    category_overrides: BTreeMap<String, String>,
    unexplained_gap_threshold_seconds: f64,

    category_seconds: BTreeMap<String, f64>,
    app_seconds: BTreeMap<String, f64>,
    other_app_seconds: BTreeMap<String, f64>,
    keyboard_events: i64,
    mouse_move_events: i64,
    mouse_click_events: i64,
    idle_seconds: f64,
    active_seconds: f64,
    closed_segments: Vec<ActivitySegment>,
    closed_gaps: Vec<UnexplainedGap>,

    // Survive `flush()` — only a real event (category change / idle ending)
    // closes these, never a bucket boundary (see module doc comment).
    current_segment_category: Option<String>,
    current_segment_started_at: Option<DateTime<Utc>>,
    idle_started_at: Option<DateTime<Utc>>,
}

impl BucketAccumulator {
    pub fn new(
        consent: Consent,
        category_overrides: BTreeMap<String, String>,
        unexplained_gap_threshold_seconds: f64,
    ) -> Self {
        BucketAccumulator {
            consent,
            category_overrides,
            unexplained_gap_threshold_seconds,
            category_seconds: BTreeMap::new(),
            app_seconds: BTreeMap::new(),
            other_app_seconds: BTreeMap::new(),
            keyboard_events: 0,
            mouse_move_events: 0,
            mouse_click_events: 0,
            idle_seconds: 0.0,
            active_seconds: 0.0,
            closed_segments: Vec::new(),
            closed_gaps: Vec::new(),
            current_segment_category: None,
            current_segment_started_at: None,
            idle_started_at: None,
        }
    }

    fn segments_enabled(&self) -> bool {
        // Segments are categories over time — with no active_app_category
        // signal there is nothing for a segment to be a segment OF.
        self.consent.active_app_category && self.consent.activity_segments
    }

    fn close_current_segment(&mut self, ended_at: DateTime<Utc>) {
        let (Some(category), Some(started_at)) = (
            self.current_segment_category.take(),
            self.current_segment_started_at.take(),
        ) else {
            return;
        };
        let duration = (ended_at - started_at).num_milliseconds() as f64 / 1000.0;
        if duration > 0.0 {
            self.closed_segments.push(ActivitySegment {
                category,
                started_at,
                ended_at,
                duration_seconds: duration,
            });
        }
    }

    fn close_current_gap(&mut self, ended_at: DateTime<Utc>) {
        let Some(started_at) = self.idle_started_at.take() else {
            return;
        };
        let duration = (ended_at - started_at).num_milliseconds() as f64 / 1000.0;
        if self.consent.unexplained_gaps && duration >= self.unexplained_gap_threshold_seconds {
            self.closed_gaps.push(UnexplainedGap {
                started_at,
                ended_at,
                duration_seconds: duration,
            });
        }
    }

    /// Mirrors `Aggregator._accumulate` field-for-field, including the
    /// exact consent-gating order (`category_seconds` before `app_seconds`,
    /// `app_seconds` always populated when its double-gate is satisfied
    /// even for the unknown-process placeholder, `other_app_seconds` only
    /// for ticks whose category is `UNKNOWN_CATEGORY`).
    pub fn accumulate(&mut self, tick: &Tick) {
        let now = tick.occurred_at;

        if tick.is_idle {
            self.idle_seconds += tick.interval_seconds;
            if self.idle_started_at.is_none() {
                self.idle_started_at = Some(now);
            }
            if self.segments_enabled() {
                self.close_current_segment(now); // idling always breaks a segment
            }
        } else {
            self.close_current_gap(now); // activity resumed — the gap is over
            self.active_seconds += tick.interval_seconds;
            let mut category = None;

            if self.consent.active_app_category {
                let resolved = tick.category_override.clone().unwrap_or_else(|| {
                    categorize(
                        tick.active_process_name.as_deref(),
                        Some(&self.category_overrides),
                    )
                });
                *self.category_seconds.entry(resolved.clone()).or_insert(0.0) +=
                    tick.interval_seconds;

                if self.consent.app_detail {
                    let app_key = tick
                        .active_process_name
                        .clone()
                        .unwrap_or_else(|| UNKNOWN_APP_LABEL.to_string());
                    *self.app_seconds.entry(app_key.clone()).or_insert(0.0) +=
                        tick.interval_seconds;
                    if resolved == UNKNOWN_CATEGORY {
                        *self.other_app_seconds.entry(app_key).or_insert(0.0) +=
                            tick.interval_seconds;
                    }
                }
                category = Some(resolved);
            }

            if self.segments_enabled() {
                if let Some(category) = &category {
                    if self.current_segment_category.as_deref() != Some(category.as_str()) {
                        self.close_current_segment(now);
                        self.current_segment_category = Some(category.clone());
                        self.current_segment_started_at = Some(now);
                    }
                }
            }
        }

        if self.consent.input_activity_counts {
            self.keyboard_events += tick.keyboard_events;
            self.mouse_move_events += tick.mouse_move_events;
            self.mouse_click_events += tick.mouse_click_events;
        }
    }

    /// Mirrors `Aggregator._flush`'s construction of the `signals` dict
    /// exactly, including which fields are `None` vs an always-present
    /// (possibly empty) map based purely on consent — never based on
    /// whether anything was actually observed. `git_commits_count` is
    /// supplied by the caller (git-repository scanning is a separate,
    /// platform-agnostic side channel in the Python source —
    /// `core/git_activity.py` — out of this module's scope; see SUMMARY.md).
    /// Resets bucket sums only — NOT the open segment/gap state, matching
    /// `_reset_bucket()`'s documented behavior in the Python source exactly.
    pub fn flush(&mut self, git_commits_count: Option<i64>) -> Signals {
        let signals = Signals {
            active_app_category_seconds: self
                .consent
                .active_app_category
                .then(|| self.category_seconds.clone()),
            input_activity_events: self.consent.input_activity_counts.then_some(
                InputActivityEvents {
                    keyboard: self.keyboard_events,
                    mouse_move: self.mouse_move_events,
                    mouse_click: self.mouse_click_events,
                },
            ),
            idle_seconds: self.consent.idle_tracking.then_some(self.idle_seconds),
            active_seconds: self.active_seconds,
            activity_segments: self
                .segments_enabled()
                .then(|| self.closed_segments.clone()),
            unexplained_gaps: self
                .consent
                .unexplained_gaps
                .then(|| self.closed_gaps.clone()),
            git_commits_count,
            app_seconds: (self.consent.active_app_category && self.consent.app_detail)
                .then(|| self.app_seconds.clone()),
            other_app_seconds: (self.consent.active_app_category && self.consent.app_detail)
                .then(|| self.other_app_seconds.clone()),
        };

        self.category_seconds.clear();
        self.app_seconds.clear();
        self.other_app_seconds.clear();
        self.keyboard_events = 0;
        self.mouse_move_events = 0;
        self.mouse_click_events = 0;
        self.idle_seconds = 0.0;
        self.active_seconds = 0.0;
        self.closed_segments.clear();
        self.closed_gaps.clear();

        signals
    }
}
