//! Direct port of `agent/core/categories.py`. Field-for-field, entry-for-entry
//! parity with the Python source is the point of this module — see
//! `tests/golden_fixture_tests.rs`, which replays fixtures generated by
//! running the REAL, unmodified Python code
//! (`artifacts/desktop-client/AG-006/generate_golden_fixtures.py`), not a
//! hand-guessed re-derivation of what it probably does.

use std::collections::{BTreeMap, BTreeSet};

/// Mirrors `categories.py::DEFAULT_CATEGORY_MAP` — same keys, same values,
/// same set. Order here is irrelevant (unlike `title_classifier`'s rules):
/// this is a plain lookup table, not first-match-wins.
const DEFAULT_CATEGORY_MAP: &[(&str, &str)] = &[
    // Browsers
    ("chrome.exe", "browser"),
    ("msedge.exe", "browser"),
    ("firefox.exe", "browser"),
    ("brave.exe", "browser"),
    ("opera.exe", "browser"),
    ("yandex.exe", "browser"),
    // IDE / development
    ("code.exe", "ide"),
    ("devenv.exe", "ide"),
    ("pycharm64.exe", "ide"),
    ("idea64.exe", "ide"),
    ("webstorm64.exe", "ide"),
    ("sublime_text.exe", "ide"),
    ("notepad++.exe", "ide"),
    ("rider64.exe", "ide"),
    ("phpstorm64.exe", "ide"),
    ("clion64.exe", "ide"),
    ("datagrip64.exe", "ide"),
    ("goland64.exe", "ide"),
    ("rubymine64.exe", "ide"),
    ("vmconnect.exe", "ide"),
    // Terminals
    ("cmd.exe", "terminal"),
    ("powershell.exe", "terminal"),
    ("pwsh.exe", "terminal"),
    ("windowsterminal.exe", "terminal"),
    ("wt.exe", "terminal"),
    // Communication
    ("slack.exe", "communication"),
    ("teams.exe", "communication"),
    ("ms-teams.exe", "communication"),
    ("discord.exe", "communication"),
    ("outlook.exe", "communication"),
    ("thunderbird.exe", "communication"),
    ("telegram.exe", "communication"),
    ("zoom.exe", "communication"),
    // Office / documents
    ("winword.exe", "office"),
    ("excel.exe", "office"),
    ("powerpnt.exe", "office"),
    ("onenote.exe", "office"),
    ("acrobat.exe", "office"),
    ("notion.exe", "office"),
    // Task trackers / CRM
    ("bitrix24.exe", "task_tracker"),
    // System
    ("explorer.exe", "system"),
    ("searchapp.exe", "system"),
    ("shellexperiencehost.exe", "system"),
    // Media
    ("spotify.exe", "media"),
    ("vlc.exe", "media"),
    // Games
    ("steam.exe", "games"),

    // --- Linux equivalents ---
    // The table above is a direct port of the original Windows-only
    // Python source (see module doc comment) and never gained Linux
    // process names at all -- meaning EVERY Linux process fell through
    // to "other" regardless of what it actually was, confirmed live:
    // a real Ubuntu install reported "chrome"/"ptyxis" once process-name
    // resolution started working (AG-LNX-002/the GNOME extension), and
    // both landed in "other" until these entries existed. `/proc/<pid>/
    // comm` is truncated to 15 characters by the kernel (`TASK_COMM_LEN`
    // is 16 bytes including the NUL) -- entries below use the actual
    // truncated form where a real binary name exceeds that, not the
    // full name, since that truncated string is exactly what this
    // function receives and compares against.
    // Browsers
    ("chrome", "browser"),
    ("firefox", "browser"),
    ("firefox-bin", "browser"),
    ("brave", "browser"),
    ("chromium", "browser"),
    ("chromium-browse", "browser"), // truncated "chromium-browser"
    ("opera", "browser"),
    ("vivaldi-bin", "browser"),
    ("msedge", "browser"), // Edge for Linux
    ("yandex-browser", "browser"),
    // IDE / development
    ("code", "ide"), // VS Code
    ("code-oss", "ide"),
    ("codium", "ide"), // VSCodium
    ("pycharm", "ide"),
    ("idea", "ide"), // IntelliJ IDEA
    ("clion", "ide"),
    ("goland", "ide"),
    ("webstorm", "ide"),
    ("rider", "ide"),
    ("phpstorm", "ide"),
    ("datagrip", "ide"),
    ("rubymine", "ide"),
    ("sublime_text", "ide"),
    // No Linux equivalent exists for devenv.exe (Visual Studio proper),
    // notepad++.exe, or vmconnect.exe (Hyper-V console) -- none ported,
    // not an oversight.
    // Terminals
    ("ptyxis", "terminal"), // GNOME's current default terminal (GNOME 46+)
    ("gnome-terminal-", "terminal"), // truncated "gnome-terminal-server"
    ("konsole", "terminal"), // KDE's default terminal
    ("xterm", "terminal"),
    ("alacritty", "terminal"),
    ("kitty", "terminal"),
    ("terminator", "terminal"),
    ("tilix", "terminal"),
    ("xfce4-terminal", "terminal"),
    ("urxvt", "terminal"),
    ("foot", "terminal"), // wlroots-native terminal
    ("wezterm-gui", "terminal"),
    ("st", "terminal"), // suckless terminal
    // Communication
    ("slack", "communication"),
    ("discord", "communication"),
    ("telegram", "communication"), // the actual Telegram Desktop binary name
    ("telegram-deskt", "communication"), // truncated "telegram-desktop" (some packagings)
    ("thunderbird", "communication"),
    ("teams-for-linux", "communication"),
    ("zoom", "communication"),
    ("skypeforlinux", "communication"),
    ("element-desktop", "communication"),
    ("signal-desktop", "communication"),
    ("mattermost-deskt", "communication"), // truncated "mattermost-desktop"
    // No native Linux Outlook exists -- not ported.
    // Office / documents
    ("soffice.bin", "office"), // LibreOffice's actual process name (also covers OnlyOffice's LO-based fork)
    // Task trackers / CRM
    // No native Linux Bitrix24 desktop client -- not ported.
    // System
    ("nautilus", "system"), // GNOME Files
    ("dolphin", "system"), // KDE's file manager
    ("nemo", "system"), // Cinnamon's file manager
    ("thunar", "system"), // XFCE's file manager
    // Media
    ("vlc", "media"),
    ("spotify", "media"),
    // Games
    ("lutris", "games"),
    ("heroic", "games"), // Heroic Games Launcher (Epic/GOG on Linux)
    ("steam", "games"),
];

pub const UNKNOWN_CATEGORY: &str = "other";

/// Mirrors `categories.py::GENERIC_UTILITY_KEYWORDS` exactly, including the
/// non-obvious fact that a match maps to `"system"`, not `UNKNOWN_CATEGORY`.
const GENERIC_UTILITY_KEYWORDS: &[&str] = &[
    "vpn",
    "update",
    "launcher",
    "helper",
    "installer",
    "setup",
    "service",
];

const CATEGORY_LABELS: &[(&str, &str)] = &[
    ("ide", "IDE"),
    ("browser", "Браузер"),
    ("terminal", "Терминал"),
    ("communication", "Коммуникации"),
    ("office", "Офис"),
    ("task_tracker", "Трекер задач"),
    ("crm", "CRM"),
    ("system", "Система"),
    ("media", "Медиа"),
    ("games", "Игры"),
    ("other", "Другое"),
];

pub fn category_label(category: &str) -> String {
    CATEGORY_LABELS
        .iter()
        .find(|(key, _)| *key == category)
        .map(|(_, label)| label.to_string())
        .unwrap_or_else(|| category.to_string())
}

/// Returns the category for `process_name`, never inspecting window title
/// text. Mirrors `categorize()`'s exact precedence: explicit `overrides`
/// first, then the built-in map, then the generic-utility-keyword
/// heuristic (→ `"system"`), then `UNKNOWN_CATEGORY` as the final fallback.
pub fn categorize(
    process_name: Option<&str>,
    overrides: Option<&BTreeMap<String, String>>,
) -> String {
    let Some(process_name) = process_name else {
        return UNKNOWN_CATEGORY.to_string();
    };
    let name = process_name.trim().to_lowercase();
    if name.is_empty() {
        return UNKNOWN_CATEGORY.to_string();
    }

    if let Some(overrides) = overrides {
        if let Some(category) = overrides.get(&name) {
            return category.clone();
        }
    }

    if let Some((_, category)) = DEFAULT_CATEGORY_MAP.iter().find(|(key, _)| *key == name) {
        return category.to_string();
    }

    if GENERIC_UTILITY_KEYWORDS
        .iter()
        .any(|keyword| name.contains(keyword))
    {
        return "system".to_string();
    }

    UNKNOWN_CATEGORY.to_string()
}

/// Mirrors `processes_for_category()` — used by a future collector to know
/// "is this process already a browser?" before local title classification,
/// not related to window content.
pub fn processes_for_category(
    category: &str,
    overrides: Option<&BTreeMap<String, String>>,
) -> BTreeSet<String> {
    let mut result: BTreeSet<String> = DEFAULT_CATEGORY_MAP
        .iter()
        .filter(|(_, cat)| *cat == category)
        .map(|(name, _)| name.to_string())
        .collect();
    if let Some(overrides) = overrides {
        result.extend(
            overrides
                .iter()
                .filter(|(_, cat)| cat.as_str() == category)
                .map(|(name, _)| name.clone()),
        );
    }
    result
}
